A Ruby parser for the GIFT question format.
                              
GIFT is the format used by Moodle Learning Management System for writing multiple-choice, 
true-false, short answer, match missing word and numerical questions. 

For details on the GIFT file format see:
http://docs.moodle.org/en/GIFT

The parser is generated by Treetop parser generator. 
http://treetop.rubyforge.org/

The parser is not yet complete. It generates the syntactic tree but does not 
have all the semantic features as yet. It will give marks for answers using
pattern matching of strings to mark close answers.

See the tests to get an idea on how the parser is supposed to be used. 

See the file LICENCE for copyright details. (MIT license.)

Author: 
Stuart Coyle 2010